name: store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc:
  path: ^1.9.0
  intl: ^0.19.0
  http: ^1.2.1
  flutter_bloc: 
  sqflite: ^2.3.3+1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/

  # example:
  fonts:
    - family: Ulagadi Sans
      fonts:
        - asset: assets/fonts/UlagadiSansRegular.ttf
          weight: 400
        - asset: assets/fonts/UlagadiSansMedium.ttf
          weight: 500
        - asset: assets/fonts/UlagadiSansBold.ttf
          weight: 600
        - asset: assets/fonts/UlagadiSansLight.ttf
          weight: 300
        - asset: assets/fonts/UlagadiSansExtraBold.ttf
          weight: 700
    - family: Bell MT
      fonts:
        - asset: assets/fonts/bell-mt.ttf
          weight: 400
    - family: Perpetua Titling MT
      fonts:
        - asset: assets/fonts/PERTILI.TTF

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages